### ISSUE TITLE
RuntimeException

### ISSUE THREAD

**Issue by bbetter** [dlazaro66/QRCodeReaderView#105]
Fatal Exception: java.lang.RuntimeException
An error occured while executing doInBackground()

Fatal Exception: java.lang.RuntimeException: An error occured while executing doInBackground()
       at android.os.AsyncTask$3.done(AsyncTask.java:300)
       at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:355)
       at java.util.concurrent.FutureTask.setException(FutureTask.java:222)
       at java.util.concurrent.FutureTask.run(FutureTask.java:242)
       at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
       at java.lang.Thread.run(Thread.java:818)
Caused by java.lang.NullPointerException: Attempt to read from null array
       at com.google.zxing.common.HybridBinarizer.calculateBlackPoints(HybridBinarizer.java:184)
       at com.google.zxing.common.HybridBinarizer.getBlackMatrix(HybridBinarizer.java:79)
       at com.google.zxing.BinaryBitmap.getBlackMatrix(BinaryBitmap.java:85)
       at com.google.zxing.qrcode.QRCodeReader.decode(QRCodeReader.java:77)
       at com.google.zxing.qrcode.QRCodeReader.decode(QRCodeReader.java:64)
       at com.dlazaro66.qrcodereaderview.QRCodeReaderView$DecodeFrameTask.doInBackground(QRCodeReaderView.java:323)
       at com.dlazaro66.qrcodereaderview.QRCodeReaderView$DecodeFrameTask.doInBackground(QRCodeReaderView.java:301)
       at android.os.AsyncTask$2.call(AsyncTask.java:288)
       at java.util.concurrent.FutureTask.run(FutureTask.java:237)
       at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
       at java.lang.Thread.run(Thread.java:818)

**Comment by dlazaro66** [comment]
Can you provide more information about what are you doing?
