### ISSUE TITLE
Camera is being used after Camera.release() was called

### ISSUE THREAD

**Issue by TakWolf** [dlazaro66/QRCodeReaderView#126]
java.lang.RuntimeException: Camera is being used after Camera.release() was called
	at android.hardware.Camera.setPreviewSurface(Native Method)
	at android.hardware.Camera.setPreviewDisplay(Camera.java:800)
	at com.google.zxing.client.android.camera.open.CameraManager.openDriver(CameraManager.java:83)
	at com.dlazaro66.qrcodereaderview.QRCodeReaderView.surfaceCreated(QRCodeReaderView.java:110)
	at android.view.SurfaceView.updateWindow(SurfaceView.java:654)
	at android.view.SurfaceView$3.onPreDraw(SurfaceView.java:198)
	at android.view.ViewTreeObserver.dispatchOnPreDraw(ViewTreeObserver.java:944)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2435)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1340)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6809)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:894)
	at android.view.Choreographer.doCallbacks(Choreographer.java:696)
	at android.view.Choreographer.doFrame(Choreographer.java:631)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:880)
	at android.os.Handler.handleCallback(Handler.java:815)
	at android.os.Handler.dispatchMessage(Handler.java:104)
	at android.os.Looper.loop(Looper.java:207)
	at android.app.ActivityThread.main(ActivityThread.java:5963)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:940)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:801)

library version is 2.0.2

I did not find the way to reproduce the error， but some times it couse.

**Comment by dlazaro66** [comment]
> I did not find the way to reproduce the error

Can you provide more info? which device are you using?
