### ISSUE TITLE
Error Converting bytecode to dex

### ISSUE THREAD

**Issue by tamilairy** [dlazaro66/QRCodeReaderView#128]
I am facing error while generating APK after adding this library in my project

Error:Error converting bytecode to dex:
Cause: com.android.dex.DexException: Multiple dex files define Lcom/dlazaro66/qrcodereaderview/QRCodeReaderView$OnQRCodeReadListener;
Error:com.android.dex.DexException: Multiple dex files define Lcom/dlazaro66/qrcodereaderview/QRCodeReaderView$OnQRCodeReadListener;
Error:	at com.android.dx.merge.DexMerger.getSortedTypes(DexMerger.java:563)
Error:	at com.android.dx.merge.DexMerger.readSortableTypes(DexMerger.java:608)
Error:	at com.android.dx.merge.DexMerger.mergeClassDefs(DexMerger.java:545)
Error:	at com.android.dx.merge.DexMerger.merge(DexMerger.java:194)
Error:	at com.android.dx.merge.DexMerger.mergeDexes(DexMerger.java:167)
Error:	at com.android.builder.dexing.DexArchiveMergerCallable.mergeDexes(DexArchiveMergerCallable.java:66)
Error:	at com.android.builder.dexing.DexArchiveMergerCallable.call(DexArchiveMergerCallable.java:54)
Error:	at com.android.builder.dexing.DexArchiveMergerCallable.call(DexArchiveMergerCallable.java:37)
Error:	at java.util.concurrent.ForkJoinTask$AdaptedCallable.exec(ForkJoinTask.java:1424)
Error:	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
Error:	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
Error:	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
Error:	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
Error:java.lang.RuntimeException: com.android.build.api.transform.TransformException: com.android.dex.DexException: Multiple dex files define Lcom/dlazaro66/qrcodereaderview/QRCodeReaderView$OnQRCodeReadListener;
Error:com.android.build.api.transform.TransformException: com.android.dex.DexException: Multiple dex files define Lcom/dlazaro66/qrcodereaderview/QRCodeReaderView$OnQRCodeReadListener;
Error:com.android.dex.DexException: Multiple dex files define Lcom/dlazaro66/qrcodereaderview/QRCodeReaderView$OnQRCodeReadListener;

**Comment by dlazaro66** [comment]
Are you importing more than one library version at the same time?
