### ISSUE TITLE
crashing in jelly bean 4.2.2 please give any solution

### ISSUE THREAD

**Issue by vishal14321432** [dlazaro66/QRCodeReaderView#182]
`
E/UncaughtException: java.lang.RuntimeException: startPreview failed
        at android.hardware.Camera.startPreview(Native Method)
        at com.google.zxing.client.android.camera.CameraManager.startPreview(CameraManager.java:202)
        at com.dlazaro66.qrcodereaderview.QRCodeReaderView.surfaceChanged(QRCodeReaderView.java:250)
        at android.view.SurfaceView.updateWindow(SurfaceView.java:580)
        at android.view.SurfaceView.access$000(SurfaceView.java:86)
        at android.view.SurfaceView$3.onPreDraw(SurfaceView.java:174)
        at android.view.ViewTreeObserver.dispatchOnPreDraw(ViewTreeObserver.java:680)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1842)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:989)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:4351)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:749)
        at android.view.Choreographer.doCallbacks(Choreographer.java:562)
        at android.view.Choreographer.doFrame(Choreographer.java:532)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:735)
        at android.os.Handler.handleCallback(Handler.java:725)
        at android.os.Handler.dispatchMessage(Handler.java:92)
        at android.os.Looper.loop(Looper.java:137)
        at android.app.ActivityThread.main(ActivityThread.java:5041)
        at java.lang.reflect.Method.invokeNative(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:511)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:560)
        at dalvik.system.NativeStart.main(Native Method)`

**Comment by vishal14321432** [comment]
![Uploading vvvvvvvvvvvvvvvv.png…]()

**Comment by kyaw-min** [comment]
It's happening in Android 7 too.

```
java.lang.RuntimeException: 
  at android.hardware.Camera.startPreview (Camera.java)
  at com.google.zxing.client.android.camera.CameraManager.startPreview (CameraManager.java:2)
  at com.dlazaro66.qrcodereaderview.QRCodeReaderView.surfaceChanged (QRCodeReaderView.java:7)
  at android.view.SurfaceView.updateWindow (SurfaceView.java:634)
  at android.view.SurfaceView$3.onPreDraw (SurfaceView.java:161)
  at android.view.ViewTreeObserver.dispatchOnPreDraw (ViewTreeObserver.java:944)
  at android.view.ViewRootImpl.performTraversals (ViewRootImpl.java:2205)
  at android.view.ViewRootImpl.doTraversal (ViewRootImpl.java:1250)
  at android.view.ViewRootImpl$TraversalRunnable.run (ViewRootImpl.java:6311)
  at android.view.Choreographer$CallbackRecord.run (Choreographer.java:871)
  at android.view.Choreographer.doCallbacks (Choreographer.java:683)
  at android.view.Choreographer.doFrame (Choreographer.java:619)
  at android.view.Choreographer$FrameDisplayEventReceiver.run (Choreographer.java:857)
  at android.os.Handler.handleCallback (Handler.java:751)
  at android.os.Handler.dispatchMessage (Handler.java:95)
  at android.os.Looper.loop (Looper.java:241)
  at android.app.ActivityThread.main (ActivityThread.java:6217)
  at java.lang.reflect.Method.invoke (Method.java)
  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run (ZygoteInit.java:865)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:755)
```
