### ISSUE TITLE
Doesn;t work on Android 6

### ISSUE THREAD

**Issue by Kolyall** [dlazaro66/QRCodeReaderView#36]
```
FATAL EXCEPTION: main
                                                                     Process: com.waterworx.android, PID: 5836
                                                                     java.lang.RuntimeException: Fail to connect to camera service
                                                                         at android.hardware.Camera.<init>(Camera.java:495)
                                                                         at android.hardware.Camera.open(Camera.java:341)
                                                                         at com.google.zxing.client.android.camera.open.GingerbreadOpenCameraInterface.open(GingerbreadOpenCameraInterface.java:57)
                                                                         at com.google.zxing.client.android.camera.open.CameraManager.openDriver(CameraManager.java:77)
                                                                         at com.dlazaro66.qrcodereaderview.QRCodeReaderView.surfaceCreated(QRCodeReaderView.java:110)
                                                                         at android.view.SurfaceView.updateWindow(SurfaceView.java:583)
                                                                         at android.view.SurfaceView$3.onPreDraw(SurfaceView.java:177)
                                                                         at android.view.ViewTreeObserver.dispatchOnPreDraw(ViewTreeObserver.java:944)
                                                                         at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2055)
                                                                         at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1107)
                                                                         at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6013)
                                                                         at android.view.Choreographer$CallbackRecord.run(Choreographer.java:858)
                                                                         at android.view.Choreographer.doCallbacks(Choreographer.java:670)
                                                                         at android.view.Choreographer.doFrame(Choreographer.java:606)
                                                                         at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:844)
                                                                         at android.os.Handler.handleCallback(Handler.java:739)
                                                                         at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                         at android.os.Looper.loop(Looper.java:148)
                                                                         at android.app.ActivityThread.main(ActivityThread.java:5417)
                                                                         at java.lang.reflect.Method.invoke(Native Method)
                                                                         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
```

**Comment by havidarou** [comment]
I faced a similar issue a few days ago.

I don't know why, but you have to actually give permission in the app for
the camera, even if you included it in the manifest...

**Comment by Kolyall** [comment]
@havidarou How to do that? Can you provide a code?

**Comment by havidarou** [comment]
No need code. Go settings>apps>your app and click on permissions, turn on
the camera one.

**Comment by Kolyall** [comment]
@havidarou But the app crashes... How to avoid crashes on customer side?

**Comment by havidarou** [comment]
I don't know how to make this work without you explicitly doing that,
because android 6 has introduced permission request at runtime so it should
be permission relates, I just found this work around for testing purposes :/

**Comment by vlntdds** [comment]
Not an issue of QRCodeReaderView.
You have an issue with your application and the new permissions introduced on API23.
Read this about how to request permissions in runtime: http://developer.android.com/intl/pt-br/training/permissions/index.html

**Comment by dlazaro66** [comment]
As @vlntdds sais, this is not a QRCodeReaderView issue, since you need to check the Camera permission in runtime before using the view  (please check:  http://developer.android.com/intl/pt-br/training/permissions/index.html)
