### ISSUE TITLE
java.lang.NullPointerException: Attempt to invoke virtual method 

### ISSUE THREAD

**Issue by zekapp** [dlazaro66/QRCodeReaderView#46]
Hey Dlazaro

App crashes when I try to call startPreview() virtual methods on Marshmellow (6.0.1)

Here is the device spec:
Nexus 5
6.0.1
Here is the code that I call getCameraManager

`    @Override
    protected void onResume() {
        super.onResume();
        if (mAllPermissionGranted)
            mQrDecoderView.getCameraManager().startPreview();
    }`

Here is exception:

 `                                                              Process: com.healthed, PID: 23733
                                                              java.lang.RuntimeException: Unable to resume activity {com.healthed/com.healthed.ui.scan.qr.QrScanActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'com.google.zxing.client.android.camera.open.CameraManager com.dlazaro66.qrcodereaderview.QRCodeReaderView.getCameraManager()' on a null object reference
                                                                  at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3103)
                                                                  at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3134)
                                                                  at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2481)
                                                                  at android.app.ActivityThread.-wrap11(ActivityThread.java)
                                                                  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344)
                                                                  at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                  at android.os.Looper.loop(Looper.java:148)
                                                                  at android.app.ActivityThread.main(ActivityThread.java:5417)
                                                                  at java.lang.reflect.Method.invoke(Native Method)
                                                                  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
                                                               Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'com.google.zxing.client.android.camera.open.CameraManager com.dlazaro66.qrcodereaderview.QRCodeReaderView.getCameraManager()' on a null object reference
                                                                  at com.healthed.ui.scan.qr.QrScanActivity.onResume(QrScanActivity.java:87)
                                                                  at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1258)
                                                                  at android.app.Activity.performResume(Activity.java:6327)
                                                                  at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3092)
                                                                  at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3134) 
                                                                  at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2481) 
                                                                  at android.app.ActivityThread.-wrap11(ActivityThread.java) 
                                                                  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344) 
                                                                  at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                  at android.os.Looper.loop(Looper.java:148) 
                                                                  at android.app.ActivityThread.main(ActivityThread.java:5417) 
                                                                  at java.lang.reflect.Method.invoke(Native Method) 
                                                                  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
                                                                  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)`

**Comment by zekapp** [comment]
QRCodeREaderView needs camera permission before activity create.

`    <com.dlazaro66.qrcodereaderview.QRCodeReaderView
        android:id="@+id/qr_decoder_view"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:layout_below="@+id/toolbar"/>`

Permission should be granted before calling setContentView(). The best practice is asking the permission before launching the activity. 

Problem solved.
