### ISSUE TITLE
VerifyError

### ISSUE THREAD

**Issue by TrayEdge** [dlazaro66/QRCodeReaderView#69]
I have an error when trying to open fragment with reader view.

**E/AndroidRuntime: FATAL EXCEPTION: main java.lang.VerifyError: com/dlazaro66/qrcodereaderview/QRCodeReaderView$DecodeFrameTask
                                                                        at com.dlazaro66.qrcodereaderview.QRCodeReaderView.onPreviewFrame(QRCodeReaderView.java:211)
                                                                         at android.hardware.Camera$EventHandler.handleMessage(Camera.java:810)
                                                                         at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                         at android.os.Looper.loop(Looper.java:158)
                                                                         at android.app.ActivityThread.main(ActivityThread.java:5751)
                                                                         at java.lang.reflect.Method.invokeNative(Native Method)
                                                                         at java.lang.reflect.Method.invoke(Method.java:511)
                                                                         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1083)
                                                                         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:850)
                                                                         at dalvik.system.NativeStart.main(Native Method)**

**Comment by dlazaro66** [comment]
Please update to latest version 2.0.1 and try again. If still crashing, please re-open the issue and try to provide more info. Thanks!!
