### ISSUE TITLE
Exception if you don't call setBackCamera or setFrontCamera

### ISSUE THREAD

**Issue by MontiDreamer** [dlazaro66/QRCodeReaderView#78]
This Exception occurs, if I don't set the camera with setBackCamera on my own:

UncaughtException: java.lang.RuntimeException: Unknown camera ID 
at android.hardware.Camera._getCameraInfo(Native Method)
at android.hardware.Camera.getCameraInfo(Camera.java:244)
at com.dlazaro66.qrcodereaderview.QRCodeReaderView.getCameraDisplayOrientation(QRCodeReaderView.java:271)
at com.dlazaro66.qrcodereaderview.QRCodeReaderView.surfaceChanged(QRCodeReaderView.java:218)
at android.view.SurfaceView.updateWindow(SurfaceView.java:608)
at android.view.SurfaceView$3.onPreDraw(SurfaceView.java:179)
at android.view.ViewTreeObserver.dispatchOnPreDraw(ViewTreeObserver.java:944)
at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2059)
at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1111)
at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6017)
at android.view.Choreographer$CallbackRecord.run(Choreographer.java:858)
at android.view.Choreographer.doCallbacks(Choreographer.java:670)
at android.view.Choreographer.doFrame(Choreographer.java:606)
at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:844)
at android.os.Handler.handleCallback(Handler.java:739)
at android.os.Handler.dispatchMessage(Handler.java:95)
at android.os.Looper.loop(Looper.java:234)
at android.app.ActivityThread.main(ActivityThread.java:5526)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

**Comment by dlazaro66** [comment]
Already solved
please, for now, call `setBackCamera()` when initializing the camera (check the example) until I release a new version.
