### ISSUE TITLE
Fail to get camera info in version 2.0.1

### ISSUE THREAD

**Issue by fansmc** [dlazaro66/QRCodeReaderView#79]
`java.lang.RuntimeException: Fail to get camera info
                                                                                  at android.hardware.Camera._getCameraInfo(Native Method)
                                                                                  at android.hardware.Camera.getCameraInfo(Camera.java:237)
                                                                                  at com.dlazaro66.qrcodereaderview.QRCodeReaderView.getCameraDisplayOrientation(QRCodeReaderView.java:271)`

**Comment by rolandopt** [comment]
I'm also getting this error:

java.lang.RuntimeException: Unknown camera ID
at android.hardware.Camera._getCameraInfo(Native Method)
at android.hardware.Camera.getCameraInfo(Camera.java:388)

**Comment by tuandq2711** [comment]
I'm also getting this error:

java.lang.RuntimeException: Fail to get camera info
                                                                                at android.hardware.Camera._getCameraInfo(Native Method)
                                                                                at android.hardware.Camera.getCameraInfo(Camera.java)
                                                                                at com.dlazaro66.qrcodereaderview.QRCodeReaderView.getCameraDisplayOrientation(QRCodeReaderView.java:271)
                                                                                at com.dlazaro66.qrcodereaderview.QRCodeReaderView.surfaceChanged(QRCodeReaderView.java:218)

**Comment by aitbaali** [comment]
Same error here

```
FATAL EXCEPTION: main
java.lang.RuntimeException: Fail to get camera info
at android.hardware.Camera.getCameraInfo(Native Method)
                                                                       at com.dlazaro66.qrcodereaderview.QRCodeReaderView.getCameraDisplayOrientation(QRCodeReaderView.java:271)
                                                                       at com.dlazaro66.qrcodereaderview.QRCodeReaderView.surfaceChanged(QRCodeReaderView.java:218)
                                                                       at android.view.SurfaceView.updateWindow(SurfaceView.java:554)
                                                                       at android.view.SurfaceView.access$000(SurfaceView.java:81)
                                                                       at android.view.SurfaceView$3.onPreDraw(SurfaceView.java:169)
                                                                       at android.view.ViewTreeObserver.dispatchOnPreDraw(ViewTreeObserver.java:671)
                                                                       at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1818)
                                                                       at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:998)
                                                                       at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:4212)
                                                                       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:725)
                                                                       at android.view.Choreographer.doCallbacks(Choreographer.java:555)
                                                                       at android.view.Choreographer.doFrame(Choreographer.java:525)
                                                                       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:711)
                                                                       at android.os.Handler.handleCallback(Handler.java:615)
                                                                       at android.os.Handler.dispatchMessage(Handler.java:92)
                                                                       at android.os.Looper.loop(Looper.java:137)
                                                                       at android.app.ActivityThread.main(ActivityThread.java:4745)
                                                                       at java.lang.reflect.Method.invokeNative(Native Method)
                                                                       at java.lang.reflect.Method.invoke(Method.java:511)
                                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786)
                                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
                                                                       at dalvik.system.NativeStart.main(Native Method)
```

```
compile 'com.dlazaro66.qrcodereaderview:qrcodereaderview:2.0.1'
Android OS: 4.1.1 (API 16)
AndroidStudio: 2.1.2

Permissions
<uses-permission android:name="android.permission.CAMERA" />
<uses-feature android:name="android.hardware.camera" />
<uses-feature android:name="android.hardware.camera.autofocus" />
```

**Comment by benben2301** [comment]
Same error in S6 edge...

**Comment by hari2babloo** [comment]
Same here failed to get camera info ID -1

**Comment by dlazaro66** [comment]
Please make sure you're calling `mydecoderview.setBackCamera();` while initializing the qrcodereaderview. 

If this doesn't work, please use previous versions 2.0.0 or even 1.0.0 while I try to reproduce and fix this issue.

**Comment by benoffi7** [comment]
I have the same problem so I add

> mydecoderview.setBackCamera();

**Comment by afan2009** [comment]
+1
11-01 18:23:47.670 18900-18900/? E/AndroidRuntime: FATAL EXCEPTION: main
                                                   Process: com.example.qr_readerexample, PID: 18900
                                                   java.lang.RuntimeException: Fail to get camera info
                                                       at android.hardware.Camera._getCameraInfo(Native Method)
                                                       at android.hardware.Camera.getCameraInfo(Camera.java:269)
                                                       at com.dlazaro66.qrcodereaderview.QRCodeReaderView.getCameraDisplayOrientation(QRCodeReaderView.java:271)
                                                       at com.dlazaro66.qrcodereaderview.QRCodeReaderView.surfaceChanged(QRCodeReaderView.java:218)
                                                       at android.view.SurfaceView.updateWindow(SurfaceView.java:612)
                                                       at android.view.SurfaceView$3.onPreDraw(SurfaceView.java:185)
                                                       at android.view.ViewTreeObserver.dispatchOnPreDraw(ViewTreeObserver.java:944)
                                                       at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2036)
                                                       at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1105)
                                                       at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6204)
                                                       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:799)
                                                       at android.view.Choreographer.doCallbacks(Choreographer.java:612)
                                                       at android.view.Choreographer.doFrame(Choreographer.java:581)
                                                       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:785)
                                                       at android.os.Handler.handleCallback(Handler.java:739)
                                                       at android.os.Handler.dispatchMessage(Handler.java:95)
                                                       at android.os.Looper.loop(Looper.java:135)
                                                       at android.app.ActivityThread.main(ActivityThread.java:5593)
                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                       at java.lang.reflect.Method.invoke(Method.java:372)
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:967)
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:762)

**Comment by dlazaro66** [comment]
@afan2009 Please make sure you're calling `mydecoderview.setBackCamera();` while initializing the qrcodereaderview.

**Comment by totteire** [comment]
Same here

` java.lang.RuntimeException: Unknown camera ID
    at android.hardware.Camera._getCameraInfo(Native Method)
    at android.hardware.Camera.getCameraInfo(Camera.java:248)`

;(

**Comment by dlazaro66** [comment]
It's already solved.
@totteire please, for now, call setBackCamera() when initializing the camera (check the example) until I release a new version.

**Comment by Corical** [comment]
Is the fix linked to see how it was fixed ?

**Comment by johnnylambada** [comment]
@Corical I'm pretty sure @dlazaro66 is referring to [this commit](https://github.com/dlazaro66/QRCodeReaderView/commit/6a711baef75aab78d26d24e3a2bf7c24449f9a8a). Which -- after removing nested functions -- boils down to `mCameraManager.setPreviewCameraId(Camera.CameraInfo.CAMERA_FACING_BACK)`.
