### ISSUE TITLE
java.lang.ArrayIndexOutOfBoundsException in com.google.zxing.qrcode.decoder.BitMatrixParser.readCodewords

### ISSUE THREAD

**Issue by kiddliu** [dlazaro66/QRCodeReaderView#85]
Hi, @dlazaro66 

I'm happy with QRCodeReaderView and there is a bug found during the integration.
My device is Moto X with 6.0 system, and here is the stack trace

```
java.lang.RuntimeException: An error occurred while executing doInBackground()
    at android.os.AsyncTask$3.done(AsyncTask.java:309)
    at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:354)
    at java.util.concurrent.FutureTask.setException(FutureTask.java:223)
    at java.util.concurrent.FutureTask.run(FutureTask.java:242)
    at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:234)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
    at java.lang.Thread.run(Thread.java:818)
Caused by: java.lang.ArrayIndexOutOfBoundsException: length=121; index=121
    at com.google.zxing.qrcode.decoder.BitMatrixParser.readCodewords(BitMatrixParser.java:192)
    at com.google.zxing.qrcode.decoder.Decoder.decode(Decoder.java:149)
    at com.google.zxing.qrcode.decoder.Decoder.decode(Decoder.java:93)
    at com.google.zxing.qrcode.QRCodeReader.decode(QRCodeReader.java:78)
    at com.google.zxing.qrcode.QRCodeReader.decode(QRCodeReader.java:64)
    at com.dlazaro66.qrcodereaderview.QRCodeReaderView$DecodeFrameTask.doInBackground(QRCodeReaderView.java:323)
    at com.dlazaro66.qrcodereaderview.QRCodeReaderView$DecodeFrameTask.doInBackground(QRCodeReaderView.java:301)
    at android.os.AsyncTask$2.call(AsyncTask.java:295)
    at java.util.concurrent.FutureTask.run(FutureTask.java:237)
    ... 4 more
```

**Comment by dlazaro66** [comment]
It seems an error from Zxing decoding library. Which type of QR code are you trying to decode?
