### ISSUE TITLE
force close in fragment

### ISSUE THREAD

**Issue by meghdadya** [dlazaro66/QRCodeReaderView#94]
hi. i get this error while i am using it in fragment ? what is my mistake ? what am i done wrong ? 

      java.lang.RuntimeException: startPreview failed
                                                                             at android.hardware.Camera.startPreview(Native Method)
                                                                             at com.google.zxing.client.android.camera.CameraManager.startPreview(CameraManager.java:196)
                                                                             at com.dlazaro66.qrcodereaderview.QRCodeReaderView.surfaceChanged(QRCodeReaderView.java:220)
                                                                             at android.view.SurfaceView.updateWindow(SurfaceView.java:590)
                                                                             at android.view.SurfaceView$3.onPreDraw(SurfaceView.java:176)
                                                                             at android.view.ViewTreeObserver.dispatchOnPreDraw(ViewTreeObserver.java:847)
                                                                             at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1963)
                                                                             at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1060)
                                                                             at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5793)
                                                                             at android.view.Choreographer$CallbackRecord.run(Choreographer.java:767)
                                                                             at android.view.Choreographer.doCallbacks(Choreographer.java:580)
                                                                             at android.view.Choreographer.doFrame(Choreographer.java:550)
                                                                             at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:753)
                                                                             at android.os.Handler.handleCallback(Handler.java:739)
                                                                             at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                             at android.os.Looper.loop(Looper.java:135)
                                                                             at android.app.ActivityThread.main(ActivityThread.java:5264)
                                                                             at java.lang.reflect.Method.invoke(Native Method)
                                                                             at java.lang.reflect.Method.invoke(Method.java:372)
                                                                             at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
                                                                             at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)

**Comment by dlazaro66** [comment]
Did you try the last version? Can you provide more information?
